spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smabroApp?serverTimezone=JST
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    initialization-mode: always
    sql-script-encoding: utf-8